#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maprfs
Version  : 1
Release  : 1
URL      : http://repository.mapr.com/maven/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.jar
Source0  : http://repository.mapr.com/maven/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.jar
Source1  : http://repository.mapr.com/maven/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maprfs-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maprfs package.
Group: Data

%description data
data components for the mvn-maprfs package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.jar
/usr/share/java/.m2/repository/com/mapr/hadoop/maprfs/5.2.1-mapr/maprfs-5.2.1-mapr.pom
